theme: jekyll-theme-architect
title: Welcome to Michael Mesnikoff's Github Website Homepage!!!
description: A fun place to visit.  Please bookmark this page to keep up with changes during CS-499-Q1529


