<?php
    $page_title = "Michael's LogBook Home Page";
    require('../include/logbook-include.php');
    
    logbook_header();
    
    echo "</head>\n\n";
    echo "<BODY BGCOLOR=\"#E0E0FF\" LINK=\"#8000FF\" ALINK=\"#8000FF\" VLINK=\"#8000FF\">\n<CENTER>\n\n";

    if(!isset($_POST['u_name']) || !isset($_POST['p_word'])) {
        echo "<H1>401: Unauthorised Access<BR></h1>\n</center>\n</body>\n</html>\n";
        exit();
    }
    
    logbook_menu();
 
    $h_name = $GLOBALS['web_svr'];
    $d_base = "logbook";
?>
    
<FONT color="blue">
<H1><IMG SRC="../logbook/images/writing.gif"><BR>Michael's Latest Logbook Home Page</h1>
</center>

<HR>

<P>
Clicking on any of the images/buttons found at the left side of this document
will link you to the desired information.
<H3>Introduction:</h3>
This web site contains data generated by the Logbook Database Group.<BR>Current responsibilities include:
<UL>
<LI>Flying...
<LI>Updating this database.
<LI>More flying...
<LI><A HREF="../pages/airline-home.php">Airline Stuff Here</a>
<LI><A HREF="../pages/schedule-input.php">Schedule Input Page</a>
</ul>
</p>

<HR>
Contacting Logbook People:

<UL>
<LI>Michael Mesnikoff <A HREF="mailto:mesnikof@gsinet.net">email</a>
</ul>

<?php
    logbook_footer();
    exit();
?>
